// ***********************************************************************
// Assembly         : <Generic - Common to All>
// Author           : Mick Benner
// Created          : 10/18/2018
// ***********************************************************************
// <summary>
//     The text template (SolutionAssemblyInfo.tt) should be only included in one project.  This project should be a dependent project of
//     every other project.  Each of the child projects should include the result file (SolutionAssemblyInfo.cs) and modify the original
//     AssemblyInfo.cs to remove duplicate attributes.
// </summary>
// ***********************************************************************

// ***********************************************************************
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// ***********************************************************************

// TODO: Implement the SolutionAssemblyInfo.tt file.  Likely this will be produced via the Cake build scripts so that it isn't
// TODO: part of the project structure.  This is due to the desire to have the Directory.Build.props with includes the common
// TODO: files for all projects.  If the tt were included in the Arowana.Common there comes an issue with the auto generation of
// TODO: the file and the reference to the same output from the Directory.Build.props file.

using System;
using System.Reflection;
using System.Runtime.InteropServices;
using Arowana.Common;

[assembly: AssemblyProduct("Arowana Software")]
#if DEBUG
[assembly: AssemblyBuildMode(@"Debug")]
#else
[assembly: AssemblyBuildMode(@"Release")]
#endif

[assembly: AssemblyBuildDate("04/09/2019 01:00:00 PM")]
[assembly: CLSCompliant(true)]
[assembly: ComVisible(false)]
[assembly: AssemblyCopyright("Copyright © 2019 Blue Pine Tree Software. All rights reserved.")]